Fixing the todo example
CaravelLabs/nextjs-starter pull request #6
Opened 2023-03-30 18:37 UTC by jamesxv7

Quick demo:
![animation-todo-demo](https://user-images.githubusercontent.com/121668/228932300-a1032832-48d0-4316-9fd2-fedd8fca2d64.gif)

2023-03-30 19:40 UTC, ocasiom commented on src/pages/todo/components/todoInput.tsx
Move these components outside the pages structure, otherwise they are accessible via URL routes, for example: http://localhost:3000/todo/components/todoInput

2023-03-30 19:42 UTC, ocasiom commented on src/pages/todo/todoModel.ts
This is a good first step as a basic example, I would like us to then take it to the next step and separate model / viewmodel and add some APIs to show a more realistic end to end transaction.

2023-03-30 19:43 UTC, ocasiom requested changes
See my two comments, let's at least do the moving of the components from the pages to the modules folders. The other one about the API can be a future PR.

2023-03-31 00:03 UTC, jamesxv7 commented on src/pages/todo/components/todoInput.tsx
Oops! True, totally overlooked it. Great catch!

2023-03-31 00:05 UTC, jamesxv7 commented on src/pages/todo/todoModel.ts
Definitely, I have it on the radar as part of making a comparison between Mobx and Valtio.

2023-03-31 00:10 UTC, ocasiom approved these changes

2023-03-31 00:10 UTC, merged